#!/usr/bin/env bash

# Source: https://stackoverflow.com/questions/5947742/how-to-change-the-output-color-of-echo-in-linux
RED='\033[0;31m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

# Source: https://stackoverflow.com/questions/2924697/how-does-one-output-bold-text-in-bash
bold=$(tput bold)
normal=$(tput sgr0)

# $1 - Message
errorMsg() {
    echo -e " > - ${RED}ERROR${NC} - "${1}
}

# $1 - Message
warningMsg() {
    echo -e " > - ${YELLOW}WARNING${NC} - "${1}
}

# $1 - Message
successMsg() {
    echo -e " > - ${GREEN}SUCCESS${NC} - "${1}
}

# $1 - Message
simpleMsg() {
    echo -e " > "${1}
}

exit 0
